Support skipping API calls
api3dao/signed-api pull request #245
Opened 2024-02-28 15:52 UTC by aquarat

This PR adds support for skipping API calls.

Closes #238

2024-02-28 18:58 UTC, andreogle approved these changes

2024-02-28 20:39 UTC, bdrhn9 commented on packages/airnode-feed/src/api-requests/data-provider.ts
> +        return;
Just to note, I'd prefer to mimic exactly same behaviour with airnode which directs output of pre-processing to post-processing. One can see [here](https://github.com/api3dao/airnode/blob/59c8cd8c93f002460649e6c707abe943f0fb2b1d/packages/airnode-node/src/api/index.ts#L315).
```suggestion
        return { data: processedEndpointParameters };
```

Nit: it'd be better to inform about skipping API call in debug mode like following: 
```ts
logger.debug('Skipping API call.', { processedEndpointParameters });
```

2024-02-29 04:37 UTC, Siegrift commented on packages/airnode-feed/src/api-requests/data-provider.ts
> +        return;
Agree with Bedirhan here. I'd also add to only print out:
```ts
logger.debug('Performing API call.', { processedEndpointParameters });
```

if we are actually making an API call.

2024-02-29 09:59 UTC, aquarat commented on packages/airnode-feed/src/api-requests/data-provider.ts
> +        return;
I've added logging statements for both skipped and executed API call paths, LMK if this is not what you wanted.

Thanks @bdrhn9 I don't know how I missed that :)

2024-02-29 13:08 UTC, Siegrift requested changes
Really minor changes and it's good to go.

2024-02-29 13:08 UTC, Siegrift commented on packages/airnode-feed/src/api-requests/data-provider.test.ts
> +    jest.clearAllMocks();
Is this required? We have [this](https://github.com/api3dao/signed-api/blob/73f53ef80cfcbf6f2418fa56194ab8833cac5da8/jest.config.js#L13) in the config which should do that automatically afaik.

2024-02-29 13:08 UTC, Siegrift commented on packages/airnode-feed/src/api-requests/data-provider.ts
> +      logger.debug('Performing API call.', { processedEndpointParameters });
You forgot to remove the call on line 28.

2024-02-29 13:55 UTC, aquarat commented on packages/airnode-feed/src/api-requests/data-provider.test.ts
> +    jest.clearAllMocks();
If I don't do this the test fails because `axios` has been called (it hasn't though, so it must be a leak from the previous test?). Tests should be independent/mocks should be reset, but for some reason that doesn't happen here.

2024-02-29 13:58 UTC, aquarat commented on packages/airnode-feed/src/api-requests/data-provider.ts
> +      logger.debug('Performing API call.', { processedEndpointParameters });
🙈, removed!

2024-02-29 15:46 UTC, aquarat commented on packages/airnode-feed/src/api-requests/data-provider.test.ts
> +    jest.clearAllMocks();
I think it's because `restoreMocks` in the config means jest will restore mocks to their initial implementation - but here we mock axios in the parent scope, so the initial implementation is that mock? and perhaps in those scenarios no reset occurs.

There is also a `resetMocks` config option.

2024-02-29 15:46 UTC, Siegrift commented on packages/airnode-feed/src/api-requests/data-provider.test.ts
> +    jest.clearAllMocks();
I remember now. The problem is that mocks are not affecting calls to jest.mock here https://github.com/api3dao/signed-api/blob/238-support-skipping-api-call/packages/airnode-feed/src/api-requests/data-provider.test.ts#L16

If we use the newly implemented http module fro commons, we will not need that https://github.com/api3dao/signed-api/issues/247

2024-02-29 15:47 UTC, Siegrift approved these changes
👍 LGTM

2024-02-29 15:48 UTC, aquarat commented on packages/airnode-feed/src/api-requests/data-provider.test.ts
> +    jest.clearAllMocks();
Yes, so adding `resetMocks` to the jest config fixes this issue and doesn't break any other tests.

2024-02-29 15:51 UTC, aquarat commented on packages/airnode-feed/src/api-requests/data-provider.test.ts
> +    jest.clearAllMocks();
Ah, I just saw your last comment, LMK if you're happy with enabling `resetMocks` @Siegrift

2024-02-29 15:59 UTC, Siegrift approved these changes
👍 LGTM, thanks for fixing the test.

2024-02-29 16:23 UTC, aquarat commented on packages/airnode-feed/src/api-requests/data-provider.test.ts
> +    jest.clearAllMocks();
Ah nice, thanks 👌

2024-02-29 16:23 UTC, merged